version: '3.8'

services:
  postgres:
    image: postgres:15.3-alpine
    container_name: fitkit-postgres

    environment:
      POSTGRES_USER: fitkit
      POSTGRES_PASSWORD: s3cr3t
      POSTGRES_DB: fitkit

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: