@host = http://localhost:8080
@apiBase = {{host}}/api/v1
@contentType = application/json


@testUserId = user123


### Vraag een workout suggestie op 1e
@exerciseForSuggestion = Squat
GET {{apiBase}}/workouts/suggestion?userId={{testUserId}}&exerciseName={{exerciseForSuggestion}}

### Vraag een workout suggestie op 2e
@anotherExercise = Bench Press
GET {{apiBase}}/workouts/suggestion?userId={{testUserId}}&exerciseName={{anotherExercise}}

### Log een nieuwe workout sessie voor een gebruiker
POST {{apiBase}}/workouts/users/{{testUserId}}/log
Content-Type: {{contentType}}

{
  "exerciseName": "Squat",
  "date": "2025-06-04",
  "sets": [
    { "reps": 5, "weight": 100.0 },
    { "reps": 5, "weight": 100.0 },
    { "reps": 5, "weight": 100.0 }
  ],
  "notes": "Zware squats vandaag"
}

### Registreer een nieuwe gebruiker
POST {{apiBase}}/users/register
Content-Type: {{contentType}}

{
  "username": "nieuweGebruiker2",
  "email": "nieuw@example2.com",
  "password": "wachtwoordVeilig123"
}

###  Login als een bestaande gebruiker
POST {{apiBase}}/users/login
Content-Type: {{contentType}}

{
  "usernameOrEmail": "nieuweGebruiker",
  "password": "wachtwoordVeilig123"
}