# In prod hoeft vaak alleen de test-data uit, en docs disabled
spring:
  liquibase:
    contexts: schema

  springdoc:
    api-docs:
      enabled: false
    swagger-ui:
      enabled: false

fitkit:
  api:
    jwt:
      secret: cHJvZC1zZWNyZXQtdXNlLWtleS1oZXJlLWZvci1zYWZldHk=
