DROP TABLE IF EXISTS SET_LOG;
DROP TABLE IF EXISTS EXERCISE_SESSION;
DROP TABLE IF EXISTS APP_USER;

CREATE TABLE IF NOT EXISTS APP_USER (
    ID VARCHAR(36) PRIMARY KEY,
    USERNAME VARCHAR(255) UNIQUE NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    DATE_JOINED DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS EXERCISE_SESSION (
    ID VARCHAR(36) PRIMARY KEY,
    USER_ID VARCHAR(36) NOT NULL,
    EXERCISE_NAME VARCHAR(255) NOT NULL,
    SESSION_DATE DATE NOT NULL,
    NOTES TEXT,
    FOREIGN KEY (USER_ID) REFERENCES APP_USER(ID)
);

CREATE TABLE IF NOT EXISTS SET_LOG (
    ID VARCHAR(36) PRIMARY KEY,
    EXERCISE_SESSION_ID VARCHAR(36) NOT NULL,
    REPS INT NOT NULL,
    WEIGHT DOUBLE NOT NULL,
    FOREIGN KEY (EXERCISE_SESSION_ID) REFERENCES EXERCISE_SESSION(ID) ON DELETE CASCADE
);